# github 项目 https://pymumu.github.io/smartdns/

# 修改 dns 为本机
# ipv4 127.0.0.1
# ipv6 ::1

# 本地 DNS 服务器仅监听 UDP 53端口
bind [::]:53

####### 仪表盘 
# 添加仪表盘插件
plugin smartdns_ui.so
# 设置仪表盘服务端口号
smartdns-ui.ip http://[::]:6080
# 设置仪表盘数据文件保存路径
data-dir /var/lib/smartdns
#######

####### 缓存 
# 持久化缓存，测试时关闭
cache-persist yes

# 缓存文件保存路径，缓存大小自动设置
cache-file /var/lib/smartdns/cache
# cache 文件保存到硬盘周期，3小时
cache-checkpoint-time 10800

# 查询条目过期时长，30分钟
rr-ttl-min 1800

# 过期缓存 
## 开启过期缓存，返回过期缓存的同时进行查询
serve-expired yes
## 过期缓存超时删除时间，3天
serve-expired-ttl 259200
## 过期缓存响应时间，3秒
serve-expired-reply-ttl 3
## 过期缓存预获取及其触发时间，6小时
prefetch-domain yes
serve-expired-prefetch-time 21600
####### 

####### 测速
# 开启双栈优选
dualstack-ip-selection yes
# 仅使用 ping 测速
speed-check-mode ping
####### 

# 若不保留任何数字 ip dns 服务器端点，将导致字符串 dns 端点本身无法被解析

####### cn 域名解析
# cn 域名解析列表
# https://cdn.jsdelivr.net/gh/Loyalsoldier/v2ray-rules-dat@release/china-list.txt
# cn 域名集合
# 使用方式：在任何使用 domain 的位置，替换为 /domain-set:[name]/
# 加载域名列表文件，设置为域名集合
domain-set -name cn_domain_set -type list -file /etc/smartdns/china-list.txt 

# cn 公共 CDN
# 基于 UDP 的 UDP/DOQ 快速解析
## 阿里 
#= server 223.6.6.6 -group cn_dns_group -exclude-default-group
#= server 2400:3200::1 -group cn_dns_group -exclude-default-group
server-quic 223.5.5.5 -group cn_dns_group -exclude-default-group -host-name dns.alidns.com
server-quic 2400:3200:baba::1 -group cn_dns_group -exclude-default-group -host-name dns.alidns.com
## 腾讯 ipv6 连接不佳
#- server 119.29.29.29 -group cn_dns_group -exclude-default-group
## 字节跳动 连接不佳
## onedns.net
server 117.50.22.22 -group cn_dns_group -exclude-default-group
server 2400:7fc0:849e:200::4 -group cn_dns_group -exclude-default-group

# 设置 cn 域名集合与 cn 服务器组的映射
domain-rules /domain-set:cn_domain_set/ -nameserver cn_dns_group
#######

####### DNS 服务器列表
# https://adguard-dns.io/kb/general/dns-providers
# https://github.com/curl/curl/wiki/DNS-over-HTTPS
# https://dnsprivacy.org/public_resolvers
#######

# 减少端点总数
## `#=`注释掉可用的重复端点，
## `#-`注释掉延迟稍高或成功率稍低的可用端点

####### 基于 UDP 的 DOH3/DOQ 快速解析
# DOH3 
## dns9.quad9.net
#= server-h3 9.9.9.9
#= server-h3 149.112.112.112
#= server-h3 2620:fe::fe
#= server-h3 2620:fe::fe:9
## 其他
#- server-h3 h3://nsec.arnor.org/dns-query
#- server-h3 h3://dns.kescher.at/dns-query
server-h3 h3://v.recipes/dns-query

# DOQ
## 不支持非默认的 dns-query 的其他 url 端点控制
## dns9.quad9.net
#- server-quic 9.9.9.9
#= server-quic 149.112.112.112
#- server-quic 2620:fe::9
#- server-quic 2620:fe::fe:9
## ffmuc.net 各种查询类型子域均解析到同一 ip
#- server-quic 5.1.66.255
#- server-quic 2001:678:e68:f000::
## hagezi.org
### root.hagezi.org 德国 Falkenstein
server-quic 188.34.161.210
server-quic 2a01:4f8:c17:1c66::1
### wurzn.hagezi.org 德国 Nuremberg
#- server-quic 159.69.155.94
#- server-quic 2a01:4f8:1c1c:d363::1
### juuri.hagezi.org 芬兰 Helsinki
#- server-quic 95.217.163.17
#- server-quic 2a01:4f9:c013:dc4e::1
### dnsforge.de
#- server-quic 91.99.154.175
#- server-quic 2a01:4f8:c013:29d::122
## anycast.dns.nextdns.io
server-quic 45.90.28.0
#- server-quic 2a07:a8c1::
## 其他
#- server-quic adfreedns.top
server-quic dns.luma-medien.com
#- server-quic doh.dns4all.eu
#- server-quic dns.dnsguard.pub
#- server-quic zdn.ro
#= server-quic dns.kescher.at
#= server-quic nsec.arnor.org
#- server-quic dns.caliph.dev
#- server-quic router.comss.one
#- server-quic dns.inforlogia.com
#- server-quic dns.kapite.in
#- server-quic dns.l337.site
#- server-quic dns.skrep.eu
#- server-quic dns.surfsharkdns.com
#######

# 设置域名为解析到的数字 ip 或导致异常

####### 基于 TCP 的 DOT/DOH 保留
# DOT
## cloudflare
#- server-tls 1.1.1.1
#- server-tls 2606:4700:4700::1111

# DOH
#- server-https https://dns.decloudus.com/dns-query
#######