# Problem Set 4B
# Name:
# Collaborators:

import random

# Message父类，包含明文与密文两个子类
class Message(object):
    def __init__(self, input_text):
        '''
        Initializes a Message object

        input_text (string): the message's text

        a Message object has one attribute:
            the message text
        初始化一个消息对象
        input_text（字符串）：消息的文本
        一个消息对象有一个属性：
            消息文本
        '''
        self.message_text = input_text

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''Message('{self.get_text()}')'''

    def get_text(self):
        '''
        Used to access the message text outside of the class

        Returns: (string) the message text
        用于在类外部访问消息文本
        返回：(字符串) 消息文本
        '''
        return self.message_text

    def shift_char(self, char, shift):
        '''
        Used to shift a character as described in the pset handout

        char (string): the single character to shift.
                    ASCII value in the range: 32<=ord(char)<=126
        shift (int): the amount to shift char by

        Returns: (string) the shifted character with ASCII value in the range [32, 126]
        用于按照 pset 讲义中描述的方式对字符进行移位

        char (字符串): 需要移位的单个字符。
                    ASCII 值范围：32 <= ord(char) <= 126
        shift (整数): 字符移位的量

        返回: (字符串) 移位后的字符，其 ASCII 值在 [32, 126] 范围内
        '''
        # ord返回字符的ascii码
        # chr返回作为参数的ascii码对应的字符
        shift %= 95
        res_char_num = ord(char) + shift
        if res_char_num > 126:
            res_char_num = res_char_num - 127 + 32
        # elif res_char_num < 32:
        #     res_char_num = res_char_num -32 + 127
        return chr(res_char_num) 

    def apply_pad(self, pad):
        '''
        Used to calculate the ciphertext produced by applying a one time pad to the message text.
        For each character in the text at index i shift that character by
            the amount specified by pad[i]

        pad (list of ints): a list of integers used to encrypt the message text
                        len(pad) == len(the message text)

        Returns: (string) The ciphertext produced using the one time pad
        用于计算通过将一次性密码本应用于消息文本所生成的密文。
        对于文本中索引为i的每个字符，将该字符按照
            pad[i]指定的数量进行移位

        pad（整数列表）：用于加密消息文本的整数列表
                        len(pad) == len(消息文本)

        返回值：（字符串）使用一次性密码本生成的密文
        '''
        res_text = ''
        for i in range(len(pad)):
            res_text += self.shift_char(self.message_text[i], pad[i])
        return res_text


class PlaintextMessage(Message):
    def __init__(self, input_text, pad=None):
        '''
        Initializes a PlaintextMessage object.

        input_text (string): the message's text
        pad (list of ints OR None): the pad to encrypt the input_text or None if left empty
            if pad is not None then len(pad) == len(self.input_text)

        A PlaintextMessage object inherits from Message. It has three attributes:
            the message text
            the pad (list of integers, determined by pad
                or generated randomly using self.generate_pad() if pad is None)
            the ciphertext (string, input_text encrypted using the pad)
            初始化一个PlaintextMessage对象。

        input_text（字符串）：消息的文本
        pad（整数列表或None）：用于加密input_text的pad，如果留空则为None
            如果pad不为None，则len(pad) == len(self.input_text)

        PlaintextMessage对象继承自Message类。它有三个属性：
            消息文本
            pad（整数列表，由pad决定
                如果pad为None，则使用self.generate_pad()随机生成）
            密文（字符串，使用pad加密后的input_text）
        '''
        super().__init__(input_text)
        self.pad = pad[:] if pad != None else self.generate_pad()  
        self.cipher_text = self.apply_pad(self.pad)

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''PlaintextMessage('{self.get_text()}', {self.get_pad()})'''

    def generate_pad(self):
        '''
        Generates a one time pad which can be used to encrypt the message text.

        The pad should be generated by making a new list and for each character
            in the message chosing a random number in the range [0, 110) and
            adding that number to the list.

        Returns: (list of integers) the new one time pad
        生成一个一次性密码本，可用于加密消息文本。

        该密码本应通过创建一个新列表来生成，对于消息中的每个字符，
            在范围 [0, 110) 内选择一个随机数，并将该数添加到列表中。

        返回：(整数列表) 新的一次性密码本
        '''
        # random.randint(a,b) 返回a到b之间的随机整数
        return [random.randint(0, 109) for i in range(len(self.message_text))]

    def get_pad(self):
        '''
        Used to safely access your one time pad outside of the class

        Returns: (list of integers) a COPY of your pad
        用于在类外安全访问您的一次性密码本

        返回：（整数列表）您的密码本的副本
        '''
        return self.pad[:]

    def get_ciphertext(self):
        '''
        Used to access the ciphertext produced by applying pad to the message text

        Returns: (string) the ciphertext
        用于访问通过将填充应用于消息文本生成的密文

        返回：（字符串）密文
        '''
        return self.cipher_text

    def change_pad(self, new_pad):
        '''
        Changes the pad used to encrypt the message text and updates any other
        attributes that are determined by the pad.

        new_pad (list of ints): the new one time pad that should be associated with this message.
            len(new_pad) == len(the message text)

        Returns: nothing
        更改用于加密消息文本的密码本，并更新由密码本决定的其他属性。

        new_pad（整数列表）：应与该消息关联的新一次性密码本。
            len(new_pad) == len(消息文本)

        返回值：无
        '''
        self.pad = new_pad[:len(self.message_text)]
        self.cipher_text = self.apply_pad(self.pad)


class EncryptedMessage(Message):
    def __init__(self, input_text):
        '''
        Initializes an EncryptedMessage object

        input_text (string): the ciphertext of the message

        an EncryptedMessage object inherits from Message. It has one attribute:
            the message text (ciphertext)
            初始化一个EncryptedMessage对象

        input_text (字符串): 消息的密文

        EncryptedMessage对象继承自Message类。它有一个属性：
            消息文本（密文）
        '''
        super().__init__(input_text)

    def __repr__(self):
        '''
        Returns a human readable representation of the object
        DO NOT CHANGE

        Returns: (string) A representation of the object
        '''
        return f'''EncryptedMessage('{self.get_text()}')'''

    def decrypt_message(self, pad):
        '''
        Decrypts the message text that was encrypted with pad as described in the writeup

        pad (list of ints): the new one time pad used to encrypt the message.
            len(pad) == len(the message text)

        Returns: (PlaintextMessage) the decrypted message (containing the pad)
        解密使用一次性密码本（pad）加密的消息文本，具体方法如说明文档所述。

        pad（整数列表）：用于加密消息的新一次性密码本。
            len(pad) == len(消息文本)

        返回值：（PlaintextMessage）解密后的消息（包含密码本）
        '''
        # 将密码本e修改为-e,相应修改message的位移方法
        r_pad = [-e for e in pad]
        return PlaintextMessage(self.apply_pad(r_pad), pad)
